[package]
name = "app"
version = "0.1.1"
description = "webgal-k"
authors = ["maincore_tech."]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.2.5", features = ["macos-private-api"] }
tauri-plugin-process = "2.2.0"
tauri-plugin-persisted-scope = "2.2.0"
tauri-plugin-window-state = "2.2.1"
tauri-plugin-fs = "2.2.0"

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
